In [2]:
!pip install hmmlearn

from sklearn import datasets
from hmmlearn import hmm
import numpy as np

# Loading Iris dataset
iris = datasets.load_iris()
X = iris.data


# Training the HMM model
model = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100)
model.fit(X)

# Generating a sequence of observations from the model
generated_samples, _ = model.sample(5)

print("Generated Samples:")
print(generated_samples)


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.4/160.4 kB 2.6 MB/s eta 0:00:00
Generated Samples:
[[5.28320911 3.99038062 1.16297068 0.17414756]
 [5.11822672 3.63606427 1.67169913 0.1470836 ]
 [5.39229785 3.47082515 1.3885139  0.44048052]
 [5.0014381  3.75320045 1.50631065 0.21743567]
 [4.90200207 3.53136189 1.52193991 0.16588075]]
